### ISSUE TITLE
Radius is slightly off

### ISSUE THREAD

**Issue by Crazor** [CRKatri/eggNotch#11]
On my iPhone X, the radius is slightly off. For one, it doesn‘t blend smoothly with the sides of the screen, see attached screenshot: 
![CA839476-B425-47E1-A59A-CDE95D38DD17](https://user-images.githubusercontent.com/128295/81063128-8e9d2e80-8ed7-11ea-934f-7e513416f453.png)
Edit: It‘s really hard to tell on that screenshot. Either this is due to the white background on GitHub or the iPhone slightly clips the screen.

Also, the radius appears to be slightly smaller than the lower corners. This doesn’t show on screenshots, unfortunately.

**Comment by CRKatri** [comment]
Fixed in 0.0.3
