### ISSUE TITLE
Eggnotch in Lockscreen. 

### ISSUE THREAD

**Issue by Skeam56** [CRKatri/eggNotch#2]
Be able to have eggnotch enabled in lockscreen. Thanks for the awesome tweak.

**Comment by CRKatri** [comment]
You want to be able to turn it off on the lock screen?

**Comment by Skeam56** [comment]
Enable it. It’s not enabled.

**Comment by CRKatri** [comment]
eggNotch works on the lock screen.

**Comment by Skeam56** [comment]
Not for me

**Comment by CRKatri** [comment]
Please provide device information, picture of the issue, and tweak list

**Comment by Skeam56** [comment]
Iphone x 13.3  unc0ver jb

*7-zip (POSIX)*: 16.02-1
*A-Font*: 1.7.1
*ApolloOpener*: 1.1
*AppList*: 1.5.16~beta1
*AppSync Unified*: 74.0
*APT (apt-key)*: 1.8.2-1
*APT (libapt-pkg)*: 1.8.2-1
*APT 0.7 Transitional (apt-key)*: 1:0
*APT 1.4 Transitional*: 1:0
*APT Strict (lib)*: 1.8.2-1
*APT*: 1.8.2-3
*Assuan*: 2.5.1-1
*AutoUnlockX*: 1.0.12
*Axon*: 1.0
*Base Structure*: 1-5
*BatchInstall - Online*: 2020.04.28-20.53.54
*Batchomatic*: 4.3.1
*Berkeley DB*: 6.2.32-1
*BetterAlerts*: 1.3
*BigBoss Icon Set*: 1.0
*Bourne-Again SHell*: 5.0.3-2
*ByeBreadcrumbs*: 1.0.3
*bzip2*: 1.0.6-1
*CA Certs*: 0.0.2
*CallBubble (Beta)*: 0.2.1
*CCSupport*: 1.2.2
*CenteredLargeTitles 标题居中*: 1.0.2
*Cephei*: 1.15
*CopyLog*: 1.4.1
*Core Utilities (/bin)*: 8.31-1
*Core Utilities*: 8.31-1
*Cydia Installer*: 1.1.33
*Cydia Translations*: 1.1.32~b1
*Darwin Tools*: 1.1-1
*Debian Packager*: 1.19.7-1
*Debian Utilities*: 4.8.6-1
*debugserver-10*: 10.0.0~svn-20191106+dcaf932-1
*debugserver*: 10-1
*Devy Status Bar V2*: 1.3
*Diff Utilities*: 3.6-1
*diskdev-cmds*: 593.221.1-1
*DismissProgress*: 1.0.3
*Dots 2*: 0.3.2
*DoubleCut*: 0.5
*eggNotch*: 0.0.2-2
*file*: 5.35-2
*Filza File Manager*: 3.7.2
*Find Utilities*: 4.6.0-2
*Flame*: 1.3
*FlashBack*: 4.0.1
*Flex 3*: 3~EarlyAccess4
*FoxFort Tools*: 1.1.0
*FrontPage*: 1.5.3
*gettext*: 0.19.8-1
*Gmail Midnight*: 2.0.0
*GNU Cryptography*: 1.8.3-1
*GNU Multiple Precision Arithmetic Library*: 6.1.2-1
*GnuPG Errors*: 1.32-1
*GnuPG*: 2.2.11-2
*GnuTLS*: 3.5.19-1
*grep*: 3.1-1
*gzip*: 1.9-1
*Hide Statusbar Items X(12)*: 0.3.7
*iCleaner Pro*: 7.8.2
*IconSupport*: 1.11.1
*Installer*: 5.0.3-2
*iOS Firmware*: 13.3
*iPhone Firmware (/sbin)*: 0-1
*Jailbreak Resources*: 1.0~rc1
*jbctl*: 0.2.3-1
*Juice*: 0.0.3~Beta2
*KarenLocalizer*: 1.0.5
*KarenPrefs*: 1.5
*KSBA*: 1.3.5-1
*LatchKey*: 2.1.2
*Launch Daemon Controller*: 23-1
*libclang-cpp10*: 10.0.0~svn-20191106+dcaf932-1
*libcolorpicker*: 1.6.7
*libCSColorPicker*: 1.0.3
*libCSPreferences*: 1.3.5
*libfoxfortutils*: 1.0.18
*libidn2*: 6.1.2-1
*libimagepicker*: 1.0.4
*libllvm10*: 10.0.0~svn-20191106+dcaf932-1
*libMRYIPC*: 1.0
*libnotifications*: 0.2-4
*libplist*: 2.0.0-2
*libSparkAppList*: 1.0.7
*libsparkcolourpicker*: 1.0.0
*libSparkMessage*: 1.0.0
*libswift4*: 4.2.1-2
*libtasn1*: 4.13-1
*libunistring*: 0.9.10-1
*Link Identity Editor*: 2:2.1.2+g5420cb5-1
*lotion*: 2.0
*Lotus*: 1.0
*Lune 🌙*: 1.4.2
*LZ4*: 1.7.5-1
*LZMA Utils*: 2:4.32.7-2
*mySB*: 1.2
*Nettle*: 3.4.1-1
*New Curses*: 5.9-1
*New Curses*: 6.1+20181013-1
*New GNU Portable Threads*: 1.6-1
*NiceHelper*: 2.5-6
*Notchification*: 2.0.2-3
*Opener*: 3.2.2
*OpenSSL 1.0 Libraries*: 1.0.2s-1
*OpenSSL 1.1.1 Libraries*: 1.1.1c-1
*OTADisabler*: 0.1-7
*p11-kit*: 0.23.12-1
*PanCake*: 1.1
*PencilChargingIndicator*: 1.2~b7
*PPSSPP (Dev-Working)*: 0v1.6.3-456-g6d0ed4ad0
*PreferenceLoader*: 2.2.4
*PrefixUI*: 1.2.6
*Profile Directory*: 0-1
*readline*: 8.0-1
*ReProvision*: 0.5.2~EOL
*RocketBootstrap*: 1.0.9
*SafeShutdown*: 1.60
*Saw*: 1.4.0
*ScreenshotX*: 0.3
*sed*: 4.5-1
*SelectionPlus*: 1.1
*Shadow*: 2.0.20
*shell-cmds*: 118-8
*ShortLook*: 1.0.17
*shuffle*: 1.1.4
*SimpleActivationActions*: 0.1-1
*SkinnySettings*: 1.4.3
*SmartRotate*: 1.3.6
*Snappy*: 1.3.0
*SnowBoard StatusBar Extension*: 1.0.2~Beta1
*SnowBoard*: 1.2.87~Beta2
*Substitute Support Package*: 0.1~b4
*Substrate Safe Mode*: 0.9.6003
*system-cmds*: 790.30.1-2
*Tape Archive*: 1.30-2
*Trust Cache Injector*: 0.4~b5
*uasharedtools (iOS 11)*: 2.2r-94
*uasharedtools*: 2.2r-94
*UIKit Tools*: 1.1.15-2
*unrar*: 5.6.4-1
*unzip*: 6.0+deb9u1-1
*wget*: 1.19.5-2
*Xen HTML*: 1.1.5~release
*XenInfo*: 2.2.9
*XZ Utils*: 5.2.4-4
*YT ++ for YouTube*: 1.4r-106
*zip*: 2.32-1

**Comment by CRKatri** [comment]
Please disable all other tweaks in iCleaner and tell me if the issue persists

**Comment by Skeam56** [comment]
Found that it was xenhtml I had hide lockscreen status bar. Disabled it and
it worked. Only thing it doesn’t let me hide the battery icon in my
lockscreen. Thanks!
